version: '3'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: python-fastapi
      POSTGRES_USER: phuocthanh2k03
      POSTGRES_PASSWORD: e2cDE4hoOGgI
